### ISSUE TITLE
cblas_agemm?

### ISSUE THREAD

**Issue by poulson** [PositronicsLab/Ravelin#2]
I'm a bit confused as to what routine this is supposed to be wrapping, as CBLAS does not provide MPFR support, AFAIK.

**Comment by edrumwri** [comment]
Hi Jack,

This is vestigial code from before the genesis of Ravelin (it was meant to connect our matrix arithmetic and linear algebra code to MPFR). The vestigial code is wrapped inside the C++ macro 

#ifdef BUILD_ARBITRARY_PRECISION

which is never defined- so the code is never compiled.

Regards,
E
